{{- if .Values.deployment }}
{{- if .Values.deployment.blackBoxTests }}
apiVersion: batch/v1
kind: Job
metadata:
  name: settlements-payments-system-post-deploy
  labels:
    {{- include "settlements-payments-system.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: before-hook-creation
spec:
  backoffLimit: 0
  template:
    metadata:
      name: "settlements-payments-system-post-deploy"
      labels:
        {{- include "settlements-payments-system.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "settlements-payments-system.serviceAccountName" . }}
      restartPolicy: Never
      containers:
        - name: black-box-tests
          image: "{{ .Values.deployment.blackBoxTests.repository }}:{{ .Values.deployment.blackBoxTests.tag }}"
          imagePullPolicy: IfNotPresent
          {{- if .Values.deployment.blackBoxTests.env }}
          env:
            - name: KAFKA_TEST_ENABLED
              value: "true"
            - name: BASE_URL
              value: "{{ .Values.deployment.blackBoxTests.env.baseUrl }}"
            - name: TEST_BEARER_TOKEN
              value: "{{ .Values.deployment.blackBoxTests.env.testBearerToken }}"
            - name: S3_TEST_ENABLED
              value: "true"
            - name: KAFKA_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: settlements-payments-system-msk-eventstreaming
                  key: endpoint
            - name: KAFKA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: settlements-payments-system-msk-eventstreaming
                  key: username
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: settlements-payments-system-msk-eventstreaming
                  key: password
            - name: KAFKA_TOPICS_TRANSACTIONS
              value: "{{ .Values.deployment.blackBoxTests.env.kafkaTopic }}"
            - name: KAFKA_TOPICS_PAYMENT_STATE_UPDATES
              value: "{{ .Values.deployment.blackBoxTests.env.paymentStateUpdateKafkaTopic }}"
          {{- end }}
{{- end }}
{{- end }}
