{{- if .Values.pdb.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "settlements-payments-system.fullname" . }}
  labels:
    {{- include "settlements-payments-system.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "settlements-payments-system.selectorLabels" . | nindent 6 }}
  {{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable | int }}
  {{- end }}
  {{- if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable | int }}
  {{- end }}
  {{- end -}}