// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/saltpay/settlements-payments-system/internal/domain/models"
	"github.com/saltpay/settlements-payments-system/internal/domain/ports"
	"sync"
)

// Ensure, that CheckPaymentAccountFundsAvailabilityMock does implement ports.CheckPaymentAccountFundsAvailability.
// If this is not the case, regenerate this file with moq.
var _ ports.CheckPaymentAccountFundsAvailability = &CheckPaymentAccountFundsAvailabilityMock{}

// CheckPaymentAccountFundsAvailabilityMock is a mock implementation of ports.CheckPaymentAccountFundsAvailability.
//
// 	func TestSomethingThatUsesCheckPaymentAccountFundsAvailability(t *testing.T) {
//
// 		// make and configure a mocked ports.CheckPaymentAccountFundsAvailability
// 		mockedCheckPaymentAccountFundsAvailability := &CheckPaymentAccountFundsAvailabilityMock{
// 			ExecuteFunc: func(ctx context.Context, code models.CurrencyCode, amount float64, highRisk bool) (bool, error) {
// 				panic("mock out the Execute method")
// 			},
// 		}
//
// 		// use mockedCheckPaymentAccountFundsAvailability in code that requires ports.CheckPaymentAccountFundsAvailability
// 		// and then make assertions.
//
// 	}
type CheckPaymentAccountFundsAvailabilityMock struct {
	// ExecuteFunc mocks the Execute method.
	ExecuteFunc func(ctx context.Context, code models.CurrencyCode, amount float64, highRisk bool) (bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// Execute holds details about calls to the Execute method.
		Execute []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Code is the code argument value.
			Code models.CurrencyCode
			// Amount is the amount argument value.
			Amount float64
			// HighRisk is the highRisk argument value.
			HighRisk bool
		}
	}
	lockExecute sync.RWMutex
}

// Execute calls ExecuteFunc.
func (mock *CheckPaymentAccountFundsAvailabilityMock) Execute(ctx context.Context, code models.CurrencyCode, amount float64, highRisk bool) (bool, error) {
	if mock.ExecuteFunc == nil {
		panic("CheckPaymentAccountFundsAvailabilityMock.ExecuteFunc: method is nil but CheckPaymentAccountFundsAvailability.Execute was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Code     models.CurrencyCode
		Amount   float64
		HighRisk bool
	}{
		Ctx:      ctx,
		Code:     code,
		Amount:   amount,
		HighRisk: highRisk,
	}
	mock.lockExecute.Lock()
	mock.calls.Execute = append(mock.calls.Execute, callInfo)
	mock.lockExecute.Unlock()
	return mock.ExecuteFunc(ctx, code, amount, highRisk)
}

// ExecuteCalls gets all the calls that were made to Execute.
// Check the length with:
//     len(mockedCheckPaymentAccountFundsAvailability.ExecuteCalls())
func (mock *CheckPaymentAccountFundsAvailabilityMock) ExecuteCalls() []struct {
	Ctx      context.Context
	Code     models.CurrencyCode
	Amount   float64
	HighRisk bool
} {
	var calls []struct {
		Ctx      context.Context
		Code     models.CurrencyCode
		Amount   float64
		HighRisk bool
	}
	mock.lockExecute.RLock()
	calls = mock.calls.Execute
	mock.lockExecute.RUnlock()
	return calls
}
