// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/saltpay/settlements-payments-system/internal/domain/ports"
	"sync"
)

// Ensure, that MetricsClientMock does implement ports.MetricsClient.
// If this is not the case, regenerate this file with moq.
var _ ports.MetricsClient = &MetricsClientMock{}

// MetricsClientMock is a mock implementation of ports.MetricsClient.
//
// 	func TestSomethingThatUsesMetricsClient(t *testing.T) {
//
// 		// make and configure a mocked ports.MetricsClient
// 		mockedMetricsClient := &MetricsClientMock{
// 			CountFunc: func(ctx context.Context, name string, value int64, tags []string)  {
// 				panic("mock out the Count method")
// 			},
// 			HistogramFunc: func(ctx context.Context, name string, value float64, tags []string)  {
// 				panic("mock out the Histogram method")
// 			},
// 		}
//
// 		// use mockedMetricsClient in code that requires ports.MetricsClient
// 		// and then make assertions.
//
// 	}
type MetricsClientMock struct {
	// CountFunc mocks the Count method.
	CountFunc func(ctx context.Context, name string, value int64, tags []string)

	// HistogramFunc mocks the Histogram method.
	HistogramFunc func(ctx context.Context, name string, value float64, tags []string)

	// calls tracks calls to the methods.
	calls struct {
		// Count holds details about calls to the Count method.
		Count []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Value is the value argument value.
			Value int64
			// Tags is the tags argument value.
			Tags []string
		}
		// Histogram holds details about calls to the Histogram method.
		Histogram []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Value is the value argument value.
			Value float64
			// Tags is the tags argument value.
			Tags []string
		}
	}
	lockCount     sync.RWMutex
	lockHistogram sync.RWMutex
}

// Count calls CountFunc.
func (mock *MetricsClientMock) Count(ctx context.Context, name string, value int64, tags []string) {
	if mock.CountFunc == nil {
		panic("MetricsClientMock.CountFunc: method is nil but MetricsClient.Count was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Name  string
		Value int64
		Tags  []string
	}{
		Ctx:   ctx,
		Name:  name,
		Value: value,
		Tags:  tags,
	}
	mock.lockCount.Lock()
	mock.calls.Count = append(mock.calls.Count, callInfo)
	mock.lockCount.Unlock()
	mock.CountFunc(ctx, name, value, tags)
}

// CountCalls gets all the calls that were made to Count.
// Check the length with:
//     len(mockedMetricsClient.CountCalls())
func (mock *MetricsClientMock) CountCalls() []struct {
	Ctx   context.Context
	Name  string
	Value int64
	Tags  []string
} {
	var calls []struct {
		Ctx   context.Context
		Name  string
		Value int64
		Tags  []string
	}
	mock.lockCount.RLock()
	calls = mock.calls.Count
	mock.lockCount.RUnlock()
	return calls
}

// Histogram calls HistogramFunc.
func (mock *MetricsClientMock) Histogram(ctx context.Context, name string, value float64, tags []string) {
	if mock.HistogramFunc == nil {
		panic("MetricsClientMock.HistogramFunc: method is nil but MetricsClient.Histogram was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Name  string
		Value float64
		Tags  []string
	}{
		Ctx:   ctx,
		Name:  name,
		Value: value,
		Tags:  tags,
	}
	mock.lockHistogram.Lock()
	mock.calls.Histogram = append(mock.calls.Histogram, callInfo)
	mock.lockHistogram.Unlock()
	mock.HistogramFunc(ctx, name, value, tags)
}

// HistogramCalls gets all the calls that were made to Histogram.
// Check the length with:
//     len(mockedMetricsClient.HistogramCalls())
func (mock *MetricsClientMock) HistogramCalls() []struct {
	Ctx   context.Context
	Name  string
	Value float64
	Tags  []string
} {
	var calls []struct {
		Ctx   context.Context
		Name  string
		Value float64
		Tags  []string
	}
	mock.lockHistogram.RLock()
	calls = mock.calls.Histogram
	mock.lockHistogram.RUnlock()
	return calls
}
