// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/saltpay/settlements-payments-system/internal/domain/models"
	"github.com/saltpay/settlements-payments-system/internal/domain/ports"
	"sync"
)

// Ensure, that TrackPaymentOutcomeMock does implement ports.TrackPaymentOutcome.
// If this is not the case, regenerate this file with moq.
var _ ports.TrackPaymentOutcome = &TrackPaymentOutcomeMock{}

// TrackPaymentOutcomeMock is a mock implementation of ports.TrackPaymentOutcome.
//
// 	func TestSomethingThatUsesTrackPaymentOutcome(t *testing.T) {
//
// 		// make and configure a mocked ports.TrackPaymentOutcome
// 		mockedTrackPaymentOutcome := &TrackPaymentOutcomeMock{
// 			ExecuteFunc: func(ctx context.Context, ppEvent models.PaymentProviderEvent) error {
// 				panic("mock out the Execute method")
// 			},
// 		}
//
// 		// use mockedTrackPaymentOutcome in code that requires ports.TrackPaymentOutcome
// 		// and then make assertions.
//
// 	}
type TrackPaymentOutcomeMock struct {
	// ExecuteFunc mocks the Execute method.
	ExecuteFunc func(ctx context.Context, ppEvent models.PaymentProviderEvent) error

	// calls tracks calls to the methods.
	calls struct {
		// Execute holds details about calls to the Execute method.
		Execute []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PpEvent is the ppEvent argument value.
			PpEvent models.PaymentProviderEvent
		}
	}
	lockExecute sync.RWMutex
}

// Execute calls ExecuteFunc.
func (mock *TrackPaymentOutcomeMock) Execute(ctx context.Context, ppEvent models.PaymentProviderEvent) error {
	if mock.ExecuteFunc == nil {
		panic("TrackPaymentOutcomeMock.ExecuteFunc: method is nil but TrackPaymentOutcome.Execute was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		PpEvent models.PaymentProviderEvent
	}{
		Ctx:     ctx,
		PpEvent: ppEvent,
	}
	mock.lockExecute.Lock()
	mock.calls.Execute = append(mock.calls.Execute, callInfo)
	mock.lockExecute.Unlock()
	return mock.ExecuteFunc(ctx, ppEvent)
}

// ExecuteCalls gets all the calls that were made to Execute.
// Check the length with:
//     len(mockedTrackPaymentOutcome.ExecuteCalls())
func (mock *TrackPaymentOutcomeMock) ExecuteCalls() []struct {
	Ctx     context.Context
	PpEvent models.PaymentProviderEvent
} {
	var calls []struct {
		Ctx     context.Context
		PpEvent models.PaymentProviderEvent
	}
	mock.lockExecute.RLock()
	calls = mock.calls.Execute
	mock.lockExecute.RUnlock()
	return calls
}
