// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"github.com/saltpay/settlements-payments-system/banking_circle_payment_service/adapters/http_client"
	"net/http"
	"sync"
)

// Ensure, that HTTPDoerMock does implement http_client.HTTPDoer.
// If this is not the case, regenerate this file with moq.
var _ http_client.HTTPDoer = &HTTPDoerMock{}

// HTTPDoerMock is a mock implementation of http_client.HTTPDoer.
//
// 	func TestSomethingThatUsesHTTPDoer(t *testing.T) {
//
// 		// make and configure a mocked http_client.HTTPDoer
// 		mockedHTTPDoer := &HTTPDoerMock{
// 			DoFunc: func(r *http.Request) (*http.Response, error) {
// 				panic("mock out the Do method")
// 			},
// 		}
//
// 		// use mockedHTTPDoer in code that requires http_client.HTTPDoer
// 		// and then make assertions.
//
// 	}
type HTTPDoerMock struct {
	// DoFunc mocks the Do method.
	DoFunc func(r *http.Request) (*http.Response, error)

	// calls tracks calls to the methods.
	calls struct {
		// Do holds details about calls to the Do method.
		Do []struct {
			// R is the r argument value.
			R *http.Request
		}
	}
	lockDo sync.RWMutex
}

// Do calls DoFunc.
func (mock *HTTPDoerMock) Do(r *http.Request) (*http.Response, error) {
	if mock.DoFunc == nil {
		panic("HTTPDoerMock.DoFunc: method is nil but HTTPDoer.Do was just called")
	}
	callInfo := struct {
		R *http.Request
	}{
		R: r,
	}
	mock.lockDo.Lock()
	mock.calls.Do = append(mock.calls.Do, callInfo)
	mock.lockDo.Unlock()
	return mock.DoFunc(r)
}

// DoCalls gets all the calls that were made to Do.
// Check the length with:
//     len(mockedHTTPDoer.DoCalls())
func (mock *HTTPDoerMock) DoCalls() []struct {
	R *http.Request
} {
	var calls []struct {
		R *http.Request
	}
	mock.lockDo.RLock()
	calls = mock.calls.Do
	mock.lockDo.RUnlock()
	return calls
}
