// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"bytes"
	"context"
	"github.com/saltpay/settlements-payments-system/internal/adapters/replay_payment"
	"io"
	"sync"
)

// Ensure, that S3ClientMock does implement replay_payment.S3Client.
// If this is not the case, regenerate this file with moq.
var _ replay_payment.S3Client = &S3ClientMock{}

// S3ClientMock is a mock implementation of replay_payment.S3Client.
//
// 	func TestSomethingThatUsesS3Client(t *testing.T) {
//
// 		// make and configure a mocked replay_payment.S3Client
// 		mockedS3Client := &S3ClientMock{
// 			PutBucketFileFunc: func(ctx context.Context, file *bytes.Reader, filename string) error {
// 				panic("mock out the PutBucketFile method")
// 			},
// 			ReadFileFunc: func(ctx context.Context, filename string) (io.Reader, error) {
// 				panic("mock out the ReadFile method")
// 			},
// 		}
//
// 		// use mockedS3Client in code that requires replay_payment.S3Client
// 		// and then make assertions.
//
// 	}
type S3ClientMock struct {
	// PutBucketFileFunc mocks the PutBucketFile method.
	PutBucketFileFunc func(ctx context.Context, file *bytes.Reader, filename string) error

	// ReadFileFunc mocks the ReadFile method.
	ReadFileFunc func(ctx context.Context, filename string) (io.Reader, error)

	// calls tracks calls to the methods.
	calls struct {
		// PutBucketFile holds details about calls to the PutBucketFile method.
		PutBucketFile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// File is the file argument value.
			File *bytes.Reader
			// Filename is the filename argument value.
			Filename string
		}
		// ReadFile holds details about calls to the ReadFile method.
		ReadFile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Filename is the filename argument value.
			Filename string
		}
	}
	lockPutBucketFile sync.RWMutex
	lockReadFile      sync.RWMutex
}

// PutBucketFile calls PutBucketFileFunc.
func (mock *S3ClientMock) PutBucketFile(ctx context.Context, file *bytes.Reader, filename string) error {
	if mock.PutBucketFileFunc == nil {
		panic("S3ClientMock.PutBucketFileFunc: method is nil but S3Client.PutBucketFile was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		File     *bytes.Reader
		Filename string
	}{
		Ctx:      ctx,
		File:     file,
		Filename: filename,
	}
	mock.lockPutBucketFile.Lock()
	mock.calls.PutBucketFile = append(mock.calls.PutBucketFile, callInfo)
	mock.lockPutBucketFile.Unlock()
	return mock.PutBucketFileFunc(ctx, file, filename)
}

// PutBucketFileCalls gets all the calls that were made to PutBucketFile.
// Check the length with:
//     len(mockedS3Client.PutBucketFileCalls())
func (mock *S3ClientMock) PutBucketFileCalls() []struct {
	Ctx      context.Context
	File     *bytes.Reader
	Filename string
} {
	var calls []struct {
		Ctx      context.Context
		File     *bytes.Reader
		Filename string
	}
	mock.lockPutBucketFile.RLock()
	calls = mock.calls.PutBucketFile
	mock.lockPutBucketFile.RUnlock()
	return calls
}

// ReadFile calls ReadFileFunc.
func (mock *S3ClientMock) ReadFile(ctx context.Context, filename string) (io.Reader, error) {
	if mock.ReadFileFunc == nil {
		panic("S3ClientMock.ReadFileFunc: method is nil but S3Client.ReadFile was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Filename string
	}{
		Ctx:      ctx,
		Filename: filename,
	}
	mock.lockReadFile.Lock()
	mock.calls.ReadFile = append(mock.calls.ReadFile, callInfo)
	mock.lockReadFile.Unlock()
	return mock.ReadFileFunc(ctx, filename)
}

// ReadFileCalls gets all the calls that were made to ReadFile.
// Check the length with:
//     len(mockedS3Client.ReadFileCalls())
func (mock *S3ClientMock) ReadFileCalls() []struct {
	Ctx      context.Context
	Filename string
} {
	var calls []struct {
		Ctx      context.Context
		Filename string
	}
	mock.lockReadFile.RLock()
	calls = mock.calls.ReadFile
	mock.lockReadFile.RUnlock()
	return calls
}
