// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"github.com/saltpay/settlements-payments-system/banking_circle_payment_service/adapters/http_client/authtoken"
	"sync"
	"time"
)

// Ensure, that SchedulerMock does implement authtoken.Scheduler.
// If this is not the case, regenerate this file with moq.
var _ authtoken.Scheduler = &SchedulerMock{}

// SchedulerMock is a mock implementation of authtoken.Scheduler.
//
// 	func TestSomethingThatUsesScheduler(t *testing.T) {
//
// 		// make and configure a mocked authtoken.Scheduler
// 		mockedScheduler := &SchedulerMock{
// 			AfterFuncFunc: func(d time.Duration, f func()) *time.Timer {
// 				panic("mock out the AfterFunc method")
// 			},
// 		}
//
// 		// use mockedScheduler in code that requires authtoken.Scheduler
// 		// and then make assertions.
//
// 	}
type SchedulerMock struct {
	// AfterFuncFunc mocks the AfterFunc method.
	AfterFuncFunc func(d time.Duration, f func()) *time.Timer

	// calls tracks calls to the methods.
	calls struct {
		// AfterFunc holds details about calls to the AfterFunc method.
		AfterFunc []struct {
			// D is the d argument value.
			D time.Duration
			// F is the f argument value.
			F func()
		}
	}
	lockAfterFunc sync.RWMutex
}

// AfterFunc calls AfterFuncFunc.
func (mock *SchedulerMock) AfterFunc(d time.Duration, f func()) *time.Timer {
	if mock.AfterFuncFunc == nil {
		panic("SchedulerMock.AfterFuncFunc: method is nil but Scheduler.AfterFunc was just called")
	}
	callInfo := struct {
		D time.Duration
		F func()
	}{
		D: d,
		F: f,
	}
	mock.lockAfterFunc.Lock()
	mock.calls.AfterFunc = append(mock.calls.AfterFunc, callInfo)
	mock.lockAfterFunc.Unlock()
	return mock.AfterFuncFunc(d, f)
}

// AfterFuncCalls gets all the calls that were made to AfterFunc.
// Check the length with:
//     len(mockedScheduler.AfterFuncCalls())
func (mock *SchedulerMock) AfterFuncCalls() []struct {
	D time.Duration
	F func()
} {
	var calls []struct {
		D time.Duration
		F func()
	}
	mock.lockAfterFunc.RLock()
	calls = mock.calls.AfterFunc
	mock.lockAfterFunc.RUnlock()
	return calls
}
